name: bragivino
description: "Aplicación de bodega personal de vinos."

# Versión del proyecto
version: 1.0.0+1

# Entorno de SDK
environment:
  sdk: ">=2.19.0 <3.0.0"

# Dependencias de la aplicación
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0  # Actualiza a la versión compatible con cloud_firestore
  cloud_firestore: ^5.5.0  # Actualiza a la última versión compatible
  firebase_auth: ^5.3.3  # Asegúrate de que firebase_auth también sea compatible
  firebase_auth_web: ^5.8.13  # Compatible con la web
  provider: ^6.1.2
  fluttertoast: ^8.0.9
  form_field_validator: ^1.1.0 # Para la validación de campos
  
  # Otros paquetes que puedes estar utilizando
  cupertino_icons: ^1.0.8

# Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter

# Generación de código
flutter:
  uses-material-design: true
assets:
  - assets\vino.jpg

