// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOIQ5FeQDqutQy-h3-R_pfwH_nPs6dUIw',
    appId: '1:344571389721:web:0c08e2e3bde4da489ec788',
    messagingSenderId: '344571389721',
    projectId: 'bragivino',
    authDomain: 'bragivino.firebaseapp.com',
    storageBucket: 'bragivino.firebasestorage.app',
    measurementId: 'G-GEYVHG7D88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-HSM89NH1xBmOGytcHeB3sgzjkfzj4NM',
    appId: '1:344571389721:android:36c4faff1fb04e359ec788',
    messagingSenderId: '344571389721',
    projectId: 'bragivino',
    storageBucket: 'bragivino.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ki-2Y2ekyFx-9kjNf2lD0Mklg28HWxk',
    appId: '1:344571389721:ios:5f87fac1930845669ec788',
    messagingSenderId: '344571389721',
    projectId: 'bragivino',
    storageBucket: 'bragivino.firebasestorage.app',
    iosBundleId: 'com.example.bragivino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ki-2Y2ekyFx-9kjNf2lD0Mklg28HWxk',
    appId: '1:344571389721:ios:5f87fac1930845669ec788',
    messagingSenderId: '344571389721',
    projectId: 'bragivino',
    storageBucket: 'bragivino.firebasestorage.app',
    iosBundleId: 'com.example.bragivino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOIQ5FeQDqutQy-h3-R_pfwH_nPs6dUIw',
    appId: '1:344571389721:web:8fd939160a3304399ec788',
    messagingSenderId: '344571389721',
    projectId: 'bragivino',
    authDomain: 'bragivino.firebaseapp.com',
    storageBucket: 'bragivino.firebasestorage.app',
    measurementId: 'G-PRQ9SRF922',
  );
}
